"""
agentctl — command-line interface for agent_datacenter rack management.

Usage:
    agentctl init [--instance <name>]   Bootstrap an empty rack on a clean machine.
    agentctl status                     Print rack health from the running skeleton.

The init command is idempotent: re-running on an existing install is safe.

Runtime root is $AGENT_DATACENTER_HOME (default ~/.agent_datacenter/).
Log tree is $AGENT_DATACENTER_HOME/logs/<system|comms-channel>/.
Instance data is $AGENT_DATACENTER_HOME/<instance-name>/.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import sys
from pathlib import Path

import click

from config.device_config import agent_datacenter_home, agent_datacenter_logs

log = logging.getLogger(__name__)

# Comms channels that get log directories on init
_COMMS_LOG_DIRS = ["CC.0", "Shared"]
# System-level log dirs (rack + known devices)
_SYSTEM_LOG_DIRS = ["rack", "claude_code"]


# ── Helpers ───────────────────────────────────────────────────────────────────


def _ensure_runtime_dirs(instance: str | None = None) -> Path:
    """Create the full ~/.agent_datacenter/ tree. Returns the home path."""
    home = agent_datacenter_home()
    home.mkdir(parents=True, exist_ok=True)

    logs = agent_datacenter_logs()
    logs.mkdir(parents=True, exist_ok=True)

    for sub in _SYSTEM_LOG_DIRS:
        (logs / sub).mkdir(exist_ok=True)
    for ch in _COMMS_LOG_DIRS:
        (logs / ch).mkdir(exist_ok=True)

    if instance:
        instance_dir = home / instance
        instance_dir.mkdir(exist_ok=True)
        (logs / instance).mkdir(exist_ok=True)

    return home


def _write_default_config() -> None:
    cfg = agent_datacenter_home() / "device_config.toml"
    if cfg.exists():
        return
    cfg.write_text(
        "# agent_datacenter rack configuration\n"
        "# Generated by agentctl init — edit to override defaults.\n\n"
        "[queue]\n"
        "max_queue_length = 100\n"
        "drop_newest = false\n\n"
        "[restart]\n"
        "max_restart_failures = 3\n"
        "restart_window_seconds = 60\n"
        "restart_backoff_seconds = 5.0\n\n"
        "[retention]\n"
        "retention_hours = 24\n"
    )


def _detect_postgres() -> str:
    """Return 'local', 'docker', or 'none'."""
    if shutil.which("pg_ctl"):
        return "local"
    result = subprocess.run(["docker", "info"], capture_output=True, timeout=5)
    if result.returncode == 0:
        return "docker"
    return "none"


def _detect_imap() -> str:
    """Return 'dovecot' if dovecot is in PATH, else 'stub'."""
    if shutil.which("dovecot"):
        return "dovecot"
    return "stub"


# ── Commands ──────────────────────────────────────────────────────────────────


@click.group()
@click.option("--debug", is_flag=True, help="Enable debug logging.")
def cli(debug: bool) -> None:
    """agent_datacenter rack management CLI."""
    level = logging.DEBUG if debug else logging.INFO
    logging.basicConfig(level=level, format="%(levelname)s %(name)s: %(message)s")


@cli.command()
@click.option(
    "--instance",
    default=None,
    help="Instance name to create (e.g. Igor-wild-0001). Creates instance dir and logs subdir.",
)
def init(instance: str | None) -> None:
    """
    Bootstrap an empty rack on a clean machine.

    Creates the $AGENT_DATACENTER_HOME/ runtime directory, the hierarchical
    logs/ tree (logs/<system|comms-channel>/), optional instance directory,
    writes default config, and starts the skeleton. Idempotent: safe to
    re-run on an existing install.

    Set AGENT_DATACENTER_HOME to override the default ~/.agent_datacenter/.
    """
    home = agent_datacenter_home()
    click.echo(f"agent_datacenter init  (home: {home})")

    # 1. Runtime dirs
    _ensure_runtime_dirs(instance=instance)
    logs = agent_datacenter_logs()
    click.echo(f"  runtime dir:  {home}")
    click.echo(f"  logs root:    {logs}/")
    if instance:
        click.echo(f"  instance:     {home / instance}/")
        click.echo(f"  instance log: {logs / instance}/")

    # 2. Default config
    _write_default_config()
    click.echo(f"  config:       {home / 'device_config.toml'}")

    # 3. Postgres check
    pg_mode = _detect_postgres()
    if pg_mode == "local":
        click.echo("  postgres:     local pg_ctl found — use PostgresShim to start")
    elif pg_mode == "docker":
        click.echo(
            "  postgres:     Docker available — set AGENT_DATACENTER_PG_CONTAINER "
            "and use PostgresShim"
        )
    else:
        click.echo(
            "  postgres:     not found (pg_ctl + Docker both absent) — "
            "Postgres device will be unavailable"
        )

    # 4. IMAP check
    imap_mode = _detect_imap()
    if imap_mode == "dovecot":
        click.echo("  imap:         Dovecot found — production mode")
    else:
        click.echo(
            "  imap:         Dovecot not found — Python stub will be used "
            "(set AGENT_DATACENTER_TEST_MODE=1)"
        )

    # 5. Start skeleton (in-process for init; production uses a daemon launcher)
    try:
        from skeleton.registry import DeviceRegistry

        registry = DeviceRegistry()
        from agent_datacenter.skeleton.skeleton import Skeleton

        _skel = Skeleton(registry=registry)
        devices = [d["id"] for d in registry.list_devices()]
        click.echo(f"\nRack is up.")
        click.echo(f"  Devices:  {devices}")
        click.echo(f"  Type 'agentctl status' to verify health.")
    except Exception as exc:
        click.echo(f"\n[warn] skeleton start failed: {exc}", err=True)
        click.echo(
            "  Directory and config are ready; start skeleton manually.", err=True
        )
        sys.exit(1)


@cli.command()
def status() -> None:
    """Print rack health from the running skeleton."""
    try:
        import asyncio

        from skeleton.registry import DeviceRegistry
        from agent_datacenter.skeleton.health import rack_health_async
        from agent_datacenter.skeleton.skeleton import Skeleton

        registry = DeviceRegistry()
        skel = Skeleton(registry=registry)
        result = asyncio.run(rack_health_async(skel._devices))
        if not result:
            click.echo("No live devices. (skeleton itself is not in _devices)")
            return
        for device_id, health in result.items():
            icon = "✓" if health["healthy"] else "✗"
            err = f" [{health['error']}]" if health.get("error") else ""
            click.echo(f"  {icon} {device_id}{err}")
    except Exception as exc:
        click.echo(f"error: {exc}", err=True)
        sys.exit(1)


@cli.group()
def skills() -> None:
    """Manage Claude Code skill deploys (master in agent_datacenter/skills/)."""


@skills.command("deploy")
def skills_deploy() -> None:
    """Deploy manifest-listed skills to ~/.claude/skills/ (rsync on Linux/Mac)."""
    from devices.installer import deploy_skills

    result = deploy_skills()
    click.echo(f"deployed:               {len(result.deployed)}")
    for name in result.deployed:
        click.echo(f"  + {name}")
    if result.skipped_not_for_host:
        click.echo(f"\nskipped (other hosts):  {len(result.skipped_not_for_host)}")
    if result.skipped_disabled:
        click.echo(f"skipped (disabled):     {len(result.skipped_disabled)}")
    if result.skipped_missing_source:
        click.echo(
            f"skipped (no source):    {len(result.skipped_missing_source)} — "
            f"{', '.join(result.skipped_missing_source)}"
        )
    if result.untouched_local:
        click.echo(
            f"\nuntouched local skills: {len(result.untouched_local)} — "
            f"{', '.join(result.untouched_local)}"
        )


@skills.command("status")
def skills_status() -> None:
    """Show what's managed vs local-only on this host."""
    from devices.installer import deploy_status

    info = deploy_status()
    click.echo(f"host:         {info['host']}")
    click.echo(f"manifest:     {info['manifest_path']}")
    click.echo(f"target:       {info['target']}")
    click.echo(f"managed:      {len(info['managed_for_host'])}")
    click.echo(f"present:      {len(info['present_in_target'])}")
    if info["local_only"]:
        click.echo(f"local-only:   {', '.join(info['local_only'])}")
    if info["missing_in_target"]:
        click.echo(f"NOT deployed: {', '.join(info['missing_in_target'])}")


def main() -> None:
    cli()
