"""
agentctl — command-line interface for agent_datacenter rack management.

Usage:
    agentctl init      Bootstrap an empty rack on a clean machine.
    agentctl status    Print rack health from the running skeleton.

The init command is idempotent: re-running on an existing install is safe.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

import click

log = logging.getLogger(__name__)

_RUNTIME_DIR = Path.home() / ".agent_datacenter"
_LOG_SUBDIRS = ["skeleton", "postgres", "imap"]


# ── Helpers ───────────────────────────────────────────────────────────────────


def _ensure_runtime_dirs() -> None:
    _RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    logs = _RUNTIME_DIR / "datacenter_logs"
    for sub in _LOG_SUBDIRS:
        (logs / sub).mkdir(parents=True, exist_ok=True)


def _write_default_config() -> None:
    cfg = _RUNTIME_DIR / "device_config.toml"
    if cfg.exists():
        return
    cfg.write_text(
        "# agent_datacenter rack configuration\n"
        "# Generated by agentctl init — edit to override defaults.\n\n"
        "[queue]\n"
        "max_queue_length = 100\n"
        "drop_newest = false\n\n"
        "[restart]\n"
        "max_restart_failures = 3\n"
        "restart_window_seconds = 60\n"
        "restart_backoff_seconds = 5.0\n\n"
        "[retention]\n"
        "retention_hours = 24\n"
    )


def _detect_postgres() -> str:
    """Return 'local', 'docker', or 'none'."""
    if shutil.which("pg_ctl"):
        return "local"
    result = subprocess.run(["docker", "info"], capture_output=True, timeout=5)
    if result.returncode == 0:
        return "docker"
    return "none"


def _detect_imap() -> str:
    """Return 'dovecot' if dovecot is in PATH, else 'stub'."""
    if shutil.which("dovecot"):
        return "dovecot"
    return "stub"


# ── Commands ──────────────────────────────────────────────────────────────────


@click.group()
@click.option("--debug", is_flag=True, help="Enable debug logging.")
def cli(debug: bool) -> None:
    """agent_datacenter rack management CLI."""
    level = logging.DEBUG if debug else logging.INFO
    logging.basicConfig(level=level, format="%(levelname)s %(name)s: %(message)s")


@cli.command()
def init() -> None:
    """
    Bootstrap an empty rack on a clean machine.

    Creates the ~/.agent_datacenter/ runtime directory, initialises logging
    directories, writes default config, and starts the skeleton. Idempotent:
    safe to re-run on an existing install.
    """
    click.echo("agent_datacenter init")

    # 1. Runtime dirs
    _ensure_runtime_dirs()
    click.echo(f"  runtime dir:  {_RUNTIME_DIR}")
    click.echo(
        f"  logs:         {_RUNTIME_DIR / 'datacenter_logs'}/{{skeleton,postgres,imap}}/"
    )

    # 2. Default config
    _write_default_config()
    click.echo(f"  config:       {_RUNTIME_DIR / 'device_config.toml'}")

    # 3. Postgres check
    pg_mode = _detect_postgres()
    if pg_mode == "local":
        click.echo("  postgres:     local pg_ctl found — use PostgresShim to start")
    elif pg_mode == "docker":
        click.echo(
            "  postgres:     Docker available — set AGENT_DATACENTER_PG_CONTAINER "
            "and use PostgresShim"
        )
    else:
        click.echo(
            "  postgres:     not found (pg_ctl + Docker both absent) — "
            "Postgres device will be unavailable"
        )

    # 4. IMAP check
    imap_mode = _detect_imap()
    if imap_mode == "dovecot":
        click.echo("  imap:         Dovecot found — production mode")
    else:
        click.echo(
            "  imap:         Dovecot not found — Python stub will be used "
            "(set AGENT_DATACENTER_TEST_MODE=1)"
        )

    # 5. Start skeleton (in-process for init; production uses a daemon launcher)
    try:
        from skeleton.registry import DeviceRegistry

        registry = DeviceRegistry()
        from agent_datacenter.skeleton.skeleton import Skeleton

        _skel = Skeleton(registry=registry)
        devices = [d["id"] for d in registry.list_devices()]
        click.echo(f"\nRack is up.")
        click.echo(f"  Devices:  {devices}")
        click.echo(f"  Type 'agentctl status' to verify health.")
    except Exception as exc:
        click.echo(f"\n[warn] skeleton start failed: {exc}", err=True)
        click.echo(
            "  Directory and config are ready; start skeleton manually.", err=True
        )
        sys.exit(1)


@cli.command()
def status() -> None:
    """Print rack health from the running skeleton."""
    try:
        import asyncio

        from skeleton.registry import DeviceRegistry
        from agent_datacenter.skeleton.health import rack_health_async
        from agent_datacenter.skeleton.skeleton import Skeleton

        registry = DeviceRegistry()
        skel = Skeleton(registry=registry)
        result = asyncio.run(rack_health_async(skel._devices))
        if not result:
            click.echo("No live devices. (skeleton itself is not in _devices)")
            return
        for device_id, health in result.items():
            icon = "✓" if health["healthy"] else "✗"
            err = f" [{health['error']}]" if health.get("error") else ""
            click.echo(f"  {icon} {device_id}{err}")
    except Exception as exc:
        click.echo(f"error: {exc}", err=True)
        sys.exit(1)


def main() -> None:
    cli()
